apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-action-to-kub
  labels:
    app: spring-boot-app-action-to-kub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app-action-to-kub
  template:
    metadata:
      labels:
        app: spring-boot-app-action-to-kub
    spec:
      containers:
      - name: spring-boot-app
        image: mayowa88/ultimate-cicd2:1
        ports:
        - containerPort: 8080
